name: Build APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies & Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk build-essential libffi-dev libssl-dev zip unzip git
        pip install buildozer cython

    - name: Auto accept Android SDK licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        printf "24771027a6d5815fcb22ee73f7c652686485e4db\nd56f5187479451eabf01fb78af6dfcb131a6481e\n243 narrow...\n" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        yes | sdkmanager --licenses || true

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
